/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Invoice {
  reference: string;
  date: string;
  paymentDelayInDays: number;
  customer: {
    name: string;
    address: {
      street: string;
      city: string;
      zipcode: string;
      country: string;
      state: string | null;
      additional: string | null;
    };
  };
  biller: {
    address: {
      street: string;
      city: string;
      zipcode: string;
      country: string;
      state: string | null;
      additional: string | null;
    };
    phoneNumber: string;
    email: string;
    invoiceLegalFooter: string;
  };
  itemInvoices: {
    description: string;
    quantity: number;
    unitPriceWithoutTax: number;
    taxPercent: number;
  }[];
}
